# Generated by Django 3.2.7 on 2021-11-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_restauranttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='num_guests',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='user_email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='user_first',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='user_last',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='user_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
