# Generated by Django 3.2.7 on 2021-11-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20211123_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttable',
            name='id',
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='table_num',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
