# Generated by Django 3.2.7 on 2021-11-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
