# Generated by Django 3.2.7 on 2021-11-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_remove_reservation_reserved_table_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='num_guests',
            new_name='number_of_guests',
        ),
    ]
