# Generated by Django 3.2.7 on 2021-11-28 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_rename_table_num_restauranttable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.restauranttable'),
            preserve_default=False,
        ),
    ]
