# Generated by Django 3.2.7 on 2021-12-02 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_reservation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(limit_choices_to={'is_reserved': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.restauranttable'),
        ),
    ]
