# Generated by Django 3.2.7 on 2021-12-02 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='registered_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
